spring.application.name=scada

# Porta em que o backend vai rodar
server.port=8080

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/scada_db
spring.datasource.username=postgres
spring.datasource.password=Kub3#386
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
# "update" cria ou atualiza as tabelas automaticamente com base nas suas classes Java (útil para desenvolvimento local)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
